export const markdownProseClassName = [
    "prose",
    "prose-pre:bg-[#0b0f14]",
    "prose-pre:border",
    "prose-pre:border-[var(--border)]",
    "prose-pre:my-0",
    "prose-pre:rounded-none",
    "prose-img:rounded-lg",
    "prose-img:border",
    "prose-img:border-[var(--border)]",
    "max-w-none",
    "prose-a:text-[var(--accent-cyan)]",
    "hover:prose-a:text-[var(--accent-pink)]",
    "prose-hr:border-[var(--border)]",
    "prose-code:bg-[color:rgba(34,211,238,0.08)]",
    "prose-code:px-1.5",
    "prose-code:py-0.5",
    "prose-code:rounded",
    "prose-table:border",
    "prose-table:border-[var(--border)]",
    "prose-th:border",
    "prose-td:border",
    "prose-td:px-3",
    "prose-td:py-1.5",
].join(" ");
